---
- hosts: "{{ hosts }}"
  remote_user:  "{{ user }}"
  become: True
  tasks:
    -  name: Update cache
       apt: 
          update_cache: yes
    -  name: Install packages
       apt: 
          name: "{{ package }}"
          state: present
          debug: msg = "{{ item }}"
          with_lines: 
          cat "../config/package-lists/administration.list.binary"
          cat "../config/package-lists/logging.list.binary"
