---
- hosts: "{{ hosts }}"
  remote_user:  "{{ user }}"
  become: True

  vars_prompt: 
      - name: "newhostname"
        prompt: "What is your new hostname?"
        private: no

  tasks:
     - name: "Set hostname file"
       template: 
           src: template/hostname.j2
           dest: /etc/hostname
           owner: root
           group: root
           mode: 0644

     - name: "Set hosts file"
       template: 
           src: template/hosts.j2
           dest: /etc/hosts
           owner: root
           group: root
           mode: 0644


